#!/bin/bash

if [[ "$DOCVERTER_API_URL" == "" ]]; then
    export DOCVERTER_API_URL=http://c.docverter.com/convert
fi

curl --form from=markdown \
     --form to=html \
     --form smart=true \
     --form table_of_contents=true \
     --form input_files[]=@ackn.markdown \
     --form input_files[]=@intr.markdown \
     --form input_files[]=@chap1.markdown \
     --form input_files[]=@chap2.markdown \
     --form input_files[]=@chap3.markdown \
     --form input_files[]=@conc.markdown \
     --form input_files[]=@bibl.markdown \
     $DOCVERTER_API_URL > /sdcard/phd.html

echo /sdcard/phd.html
