prynne <- readLines('data/prynne.txt')
lines <- grep('[ -][Mm]an[ ,:;\"\'.]', prynne)
png(file = 'figs/man.png', width = 700, height = 400)
hist(lines, breaks = 13, main = NULL, xlab = 'Lines', ylab = 'Appearances')
dev.off()
